name: me570
channels:
  - defaults
dependencies:
  - matplotlib=3.7.2
  - matplotlib-base
  - numpy=1.25.2
  - numpy-base=1.25.2
  - pip=23.2.1
  - python=3.10.13
  - scipy=1.11.3
  - pip:
      - cvxopt==1.3.2
